version: "3"

services:
  server:
    depends_on:
      - mongo
    build: .
    ports:
      - "8000:8000"
    networks:
      - my_network
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - my_network

networks: 
  my_network:
    driver: bridge